version:  '2'
services:
  master:
    image: cluster-spark
    container_name: spark-master
    volumes: 
      - ../data/:/data
      - ./:/spark
    networks:
      cluster-spark-network:
        ipv4_address: 172.88.0.2
    extra_hosts:
      - "slave1:172.88.0.3"
      - "slave2:172.88.0.4"
    hostname: master
    environment:
      ROLE: master
    command: ['bash','/spark/compose.sh']
    
  slave1:
    image: cluster-spark
    container_name: spark-slave1
    volumes: 
      - ../data/:/data
      - ./:/spark
    depends_on: 
      - master
    networks:
      cluster-spark-network:
        ipv4_address: 172.88.0.3
    extra_hosts:
      - "master:172.88.0.2"
      - "slave2:172.88.0.4"
    hostname: slave1
    environment:
      ROLE: slave

  slave2:
    image: cluster-spark
    container_name: spark-slave2
    volumes: 
      - ../data/:/data
      - ./:/spark
    networks:
      cluster-spark-network:
        ipv4_address: 172.88.0.4
    extra_hosts:
      - "master:172.88.0.2"
      - "slave1:172.88.0.3"
    depends_on: 
      - master
    hostname: slave2
    environment:
      ROLE: slave

networks:
  cluster-spark-network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.88.0.0/16
